logging:
  level:
    root: info
    com: warn
lesson: math

enterprice:
  name: xianbei
  age: 24
  tel: 114514
  subject:
    - 迫真空手部
    - 野兽化的先辈

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 80
---
spring:
  profiles: sit
server:
  port: 81
---
spring:
  profiles: uat
server:
  port: 82
